Refactor tests

diff --git a/runtests b/runtests
--- a/runtests
+++ b/runtests
@@ -1,4 +1,5 @@
-#!/bin/bash
+#!/usr/bin/env bash
+set -eu
 
 CURRENT_DIR="$(cd -- "$(dirname -- "$0")" &> /dev/null && pwd)"
 sh "$CURRENT_DIR/testutil/clean"
@@ -48,46 +49,56 @@ compare=(
 
 cmpprog="$CURRENT_DIR/testutil/cmpdatfile"
 
-err=0
+failed_runs=()
+failed_comparisons=()
 
 runscript()
 {
   working_dir=$(dirname "$1")
   script=$(basename "$1")
-  echo "
-Running test $1"
-  (cd "$working_dir" && bash "$script")
-  return $?
+  echo "Running test $1"
+  cd "${working_dir}"
+  if ! bash "${script}"
+  then
+      failed_runs+=("$1")
+  fi
+  cd -
 }
 
 runcompare()
 {
   working_dir=$1
-  echo "
-Running cmpdatfile in $1"
-  (cd "$working_dir" && "$cmpprog" *.cmp)
-  return $?
+  echo "Running cmpdatfile in $1"
+  cd "${working_dir}"
+  if ! bash "${cmpprog}" ./*.cmp
+  then
+      failed_comparisons+=("$1")
+  fi
+  cd -
 }
 
 for i in ${scripts[@]} ; do
     runscript "$i"
-    if [ $? -ne 0 ] ; then
-        err=1
-    fi
 done
 
 for i in ${compare[@]} ; do
     runcompare "$CURRENT_DIR/$i"
-    if [ $? -ne 0 ] ; then
-        err=1
-    fi
 done
 
-echo ""
-if [ $err -eq 0 ] ; then
-    echo "All tests successful"
-else
-    echo "One or more tests failed"
+if [[ ${#failed_runs[@]} -gt 0 ]]
+then
+    echo "Failed runs: ${failed_runs[@]}"
+fi
+if [[ ${#failed_comparisons[@]} -gt 0 ]]
+then
+    echo "Failed comparisons: ${failed_comparisons[@]}"
 fi
 
-exit $err
+if [[ ${#failed_runs[@]} -ne 0 || ${#failed_comparisons[@]} -ne 0 ]]
+then
+    echo "There were failures in either failed_runs or failed_comparisons, see above."
+    exit 1
+else
+    echo "All checks passed."
+    exit 0
+fi
diff --git a/testutil/clean b/testutil/clean
--- a/testutil/clean
+++ b/testutil/clean
@@ -1,12 +1,17 @@
-#!/bin/bash
-a=$(which nrnivmodl)
-arch="$(sed -n '/^ARCH=/s/ARCH=//p' $a)"
-echo $arch
+#!/usr/bin/env bash
 
-for i in fast ivoc nmodl npy nrniv nrnoc thread ; do
-   a="$(find $i -name $arch -print 2>/dev/null)"
-   for j in $a ; do
-      echo $j
-      rm -r -f $j
-   done
+set -eu
+
+if ! command -v nrnivmodl
+then
+    echo "nrnivmodl not found, please set it before running this script"
+    exit 1
+fi
+
+nrnivmodl_path="$(command -v nrnivmodl)"
+arch="$(sed -n '/^ARCH=/s/ARCH=//p' "${nrnivmodl_path}")"
+
+for name in fast ivoc nmodl npy nrniv nrnoc thread
+do
+   find "${name}" -name "${arch}" -prune -exec rm -fr {} \;
 done
